import json
import sys
import os


def escape_c_string(s):
    if not isinstance(s, str):
        return str(s)
    res = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    res = res.replace("??", "?\\?")
    return res


RESERVED = {
    "pascal",
    "fortran",
    "asm",
    "inline",
    "restrict",
    "typeof",
    "auto",
    "break",
    "case",
    "char",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "float",
    "for",
    "goto",
    "if",
    "int",
    "long",
    "register",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct",
    "switch",
    "typedef",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
}


def sanitize(k):
    s = (
        k.lower()
        .replace(" ", "_")
        .replace("+", "p")
        .replace("#", "sharp")
        .replace(".", "_")
        .replace("-", "_")
        .replace("'", "_")
        .replace("/", "_")
    )
    if not s or s[0].isdigit():
        s = "_" + s
    s = "".join([c if c.isalnum() or c == "_" else "_" for c in s])

    if s in RESERVED:
        s += "_lang"

    return s


def convert(input_file, output_header, output_source):
    with open(input_file, "r") as f:
        data = json.load(f)

    # Generate Header
    with open(output_header, "w") as h:
        h.write("/* Automatically generated by assets/convert_langs.py */\n")
        h.write("#ifndef LANGUAGES_DATA_H\n#define LANGUAGES_DATA_H\n\n")
        h.write('#include "types.h"\n\n')
        h.write("extern const Language g_langs_data[];\n")
        h.write("extern const int g_n_langs_data;\n\n")
        h.write("typedef struct {\n")
        for key in data.keys():
            h.write(f"    const Language* {sanitize(key)};\n")
        h.write("} LanguageStrings;\n\n")
        h.write("extern const LanguageStrings lang;\n\n")
        h.write("#endif /* LANGUAGES_DATA_H */\n")

    # Generate Source
    with open(output_source, "w") as c:
        c.write("/* Automatically generated by assets/convert_langs.py */\n")
        c.write('#include "include/languages_data.h"\n\n')
        c.write("const Language g_langs_data[] = {\n")
        for name, details in data.items():
            c.write("    {\n")
            c.write(f'        .name = "{escape_c_string(name[:31])}",\n')
            c.write(
                f'        .data_only = {"true" if details.get("data_only", False) else "false"},\n'
            )

            # lists
            for key, count_field, list_len in [
                ("extensions", "n_extensions", 32),
                ("filenames", "n_filenames", 8),
                ("shebangs", "n_shebangs", 8),
                ("keywords", "n_keywords", 32),
            ]:
                items = details.get(key, [])
                c.write(f"        .{count_field} = {len(items)},\n")
                if items:
                    c.write(f"        .{key} = {{")
                    for i, item in enumerate(items[:list_len]):
                        val = item[:31]
                        c.write(f'"{escape_c_string(val)}"')
                        if i < len(items) - 1 and i < list_len - 1:
                            c.write(", ")
                    c.write("},\n")

            # flags/strings
            c.write(
                f'        .nestedmultiline = {"true" if details.get("nestedmultiline", False) else "false"},\n'
            )
            if "complexitychecks_postfix" in details and isinstance(
                details["complexitychecks_postfix"], str
            ):
                c.write(
                    f'        .complexitychecks_postfix = "{escape_c_string(details["complexitychecks_postfix"][:31])}",\n'
                )
            if "complexitychecks_postfix_excludes" in details and isinstance(
                details["complexitychecks_postfix_excludes"], str
            ):
                c.write(
                    f'        .complexitychecks_postfix_excludes = "{escape_c_string(details["complexitychecks_postfix_excludes"][:31])}",\n'
                )

            # rules
            for key, struct_name, count_field, max_val in [
                ("line_comment", "line_comments", "n_line_comments", 8),
                ("multi_line", "multi_line", "n_multi_line", 8),
                ("quotes", "quotes", "n_quotes", 16),
            ]:
                rules = details.get(key, [])
                c.write(f"        .{count_field} = {len(rules)},\n")
                if rules:
                    c.write(f"        .{struct_name} = {{\n")
                    for rule in rules[:max_val]:
                        if key == "line_comment":
                            v = rule[:15]
                            c.write(
                                f'            {{.start = "{escape_c_string(v)}", .len = {len(v)}}},\n'
                            )
                        elif key == "multi_line":
                            start, end = rule
                            c.write(
                                f'            {{.start = "{escape_c_string(start[:15])}", .end = "{escape_c_string(end[:15])}", .start_len = {len(start[:15])}, .end_len = {len(end[:15])}, .nested = false}},\n'
                            )
                        elif key == "quotes":
                            start, end = (
                                rule.get("start", "")[:7],
                                rule.get("end", "")[:7],
                            )
                            c.write(
                                f'            {{.start = "{escape_c_string(start)}", .end = "{escape_c_string(end)}", .start_len = {len(start)}, .end_len = {len(end)}, .escape = true, .multiline = false}},\n'
                            )
                    c.write("        },\n")

            # complexity
            cxs = details.get("complexitychecks", [])
            c.write(f"        .n_complexity = {len(cxs)},\n")
            if cxs:
                c.write(f"        .complexity = {{\n")
                for val in cxs[:96]:
                    if isinstance(val, str):
                        c.write(
                            f'            {{.token = "{escape_c_string(val[:63])}", .len = {len(val[:63])}}},\n'
                        )
                c.write("        },\n")

            c.write("    },\n")
        c.write("};\n\n")
        c.write(f"const int g_n_langs_data = {len(data)};\n\n")
        c.write("const LanguageStrings lang = {\n")
        for i, key in enumerate(data.keys()):
            c.write(f"    .{sanitize(key)} = &g_langs_data[{i}],\n")
        c.write("};\n")


if __name__ == "__main__":
    convert(
        "assets/languages.json", "src/include/languages_data.h", "src/languages_data.c"
    )
