import json
import sys
import os


def escape_c_string(s):
    # Escape backslashes first, then quotes, then newlines, then trigraphs
    res = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    # Prevent trigraphs like ??= by escaping the second question mark
    res = res.replace("??", "?\\?")
    return res


def sanitize(k):
    # Convert language name to a valid C identifier
    s = (
        k.lower()
        .replace(" ", "_")
        .replace("+", "p")
        .replace("#", "sharp")
        .replace(".", "_")
        .replace("-", "_")
        .replace("'", "_")
        .replace("/", "_")
    )
    # If it starts with a digit, prepend an underscore
    if not s or s[0].isdigit():
        s = "_" + s
    # Ensure it's a valid C identifier (only alphanumeric and underscore)
    s = "".join([c if c.isalnum() or c == "_" else "_" for c in s])
    return s


def convert(input_file, output_header, output_source):
    with open(input_file, "r") as f:
        data = json.load(f)

    # Generate Header
    with open(output_header, "w") as h:
        h.write("/* Automatically generated by assets/convert_langs.py */\n")
        h.write("#ifndef LANGUAGES_DATA_H\n#define LANGUAGES_DATA_H\n\n")
        h.write('#include "types.h"\n\n')

        h.write("extern const Language g_langs_data[];\n")
        h.write("extern const int g_n_langs_data;\n\n")

        # Generate LanguageStrings struct for named access
        h.write("typedef struct {\n")
        for key in data.keys():
            h.write(f"    const Language* {sanitize(key)};\n")
        h.write("} LanguageStrings;\n\n")

        h.write("extern const LanguageStrings lang;\n\n")

        h.write("#endif /* LANGUAGES_DATA_H */\n")

    # Generate Source
    with open(output_source, "w") as c:
        c.write("/* Automatically generated by assets/convert_langs.py */\n")
        c.write('#include "include/languages_data.h"\n\n')

        # Generate the array of Language structs
        c.write("const Language g_langs_data[] = {\n")
        for name, details in data.items():
            c.write("    {\n")
            trunc_name = name[:31]
            c.write(f'        .name = "{escape_c_string(trunc_name)}",\n')
            c.write(
                f'        .data_only = {"true" if details.get("data_only", False) else "false"},\n'
            )

            # extensions
            exts = details.get("extensions", [])
            c.write(f"        .n_extensions = {len(exts)},\n")
            if exts:
                c.write(f"        .extensions = {{")
                for i, ext in enumerate(exts[:32]):  # MAX_EXTENSIONS
                    val = ext[:31]
                    c.write(f'"{escape_c_string(val)}"')
                    if i < len(exts) - 1 and i < 31:
                        c.write(", ")
                c.write("},\n")

            # line_comment
            lcs = details.get("line_comment", [])
            c.write(f"        .n_line_comments = {len(lcs)},\n")
            if lcs:
                c.write(f"        .line_comments = {{\n")
                for val in lcs[:8]:  # MAX_LINE_COMMENTS
                    v = val[:15]
                    c.write(
                        f'            {{.start = "{escape_c_string(v)}", .len = {len(v)}}},\n'
                    )
                c.write("        },\n")

            # multi_line
            mls = details.get("multi_line", [])
            c.write(f"        .n_multi_line = {len(mls)},\n")
            if mls:
                c.write(f"        .multi_line = {{\n")
                for start, end in mls[:8]:  # MAX_BLOCK_COMMENTS
                    start = start[:15]
                    end = end[:15]
                    c.write(
                        f'            {{.start = "{escape_c_string(start)}", .end = "{escape_c_string(end)}", .start_len = {len(start)}, .end_len = {len(end)}, .nested = false}},\n'
                    )
                c.write("        },\n")

            # quotes
            qs = details.get("quotes", [])
            c.write(f"        .n_quotes = {len(qs)},\n")
            if qs:
                c.write(f"        .quotes = {{\n")
                for q in qs[:16]:  # MAX_QUOTES
                    start = q.get("start", "")[:7]
                    end = q.get("end", "")[:7]
                    c.write(
                        f'            {{.start = "{escape_c_string(start)}", .end = "{escape_c_string(end)}", .start_len = {len(start)}, .end_len = {len(end)}, .escape = true, .multiline = false}},\n'
                    )
                c.write("        },\n")

            # complexity
            cxs = details.get("complexitychecks", [])
            c.write(f"        .n_complexity = {len(cxs)},\n")
            if cxs:
                c.write(f"        .complexity = {{\n")
                for val in cxs[:96]:  # MAX_COMPLEXITY_CHECKS
                    v = val[:63]
                    c.write(
                        f'            {{.token = "{escape_c_string(v)}", .len = {len(v)}}},\n'
                    )
                c.write("        },\n")

            c.write("    },\n")
        c.write("};\n\n")
        c.write(f"const int g_n_langs_data = {len(data)};\n\n")

        # Generate LanguageStrings struct implementation
        c.write("const LanguageStrings lang = {\n")
        for i, key in enumerate(data.keys()):
            c.write(f"    .{sanitize(key)} = &g_langs_data[{i}],\n")
        c.write("};\n")


if __name__ == "__main__":
    convert(
        "assets/languages.json", "src/include/languages_data.h", "src/languages_data.c"
    )
